-- PSU Dorm LIFF - Supabase schema
-- รันไฟล์นี้ใน Supabase SQL Editor ได้หลายครั้งโดยไม่ลบข้อมูลเดิม

create table if not exists public.rooms (
    room_number text primary key,
    room_type text not null default 'residential'
        check (room_type in ('residential', 'shop')),
    monthly_rent numeric(12,2) not null default 0 check (monthly_rent >= 0),
    status text not null default 'available'
        check (status in ('available', 'occupied', 'maintenance')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.students (
    student_id text primary key,
    full_name text not null,
    phone text,
    room_number text,
    line_user_id text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.students add column if not exists phone text;
alter table public.students add column if not exists room_number text;
alter table public.students add column if not exists line_user_id text;
alter table public.students add column if not exists created_at timestamptz not null default now();
alter table public.students add column if not exists updated_at timestamptz not null default now();
create unique index if not exists students_line_user_id_unique
    on public.students (line_user_id) where line_user_id is not null;

create table if not exists public.repair_tickets (
    id bigint generated by default as identity primary key,
    room_number text not null,
    repair_type text not null,
    details text not null,
    status text not null default 'รอช่างตรวจสอบ',
    accepted_by text,
    accepted_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.repair_tickets add column if not exists accepted_by text;
alter table public.repair_tickets add column if not exists accepted_at timestamptz;
alter table public.repair_tickets add column if not exists created_at timestamptz not null default now();
alter table public.repair_tickets add column if not exists updated_at timestamptz not null default now();

create table if not exists public.utility_rates (
    property_type text primary key check (property_type in ('residential', 'shop')),
    water_rate numeric(12,2) not null default 0 check (water_rate >= 0),
    electricity_rate numeric(12,2) not null default 0 check (electricity_rate >= 0),
    updated_at timestamptz not null default now()
);

insert into public.utility_rates (property_type, water_rate, electricity_rate)
values ('residential', 0, 0), ('shop', 0, 0)
on conflict (property_type) do nothing;

create table if not exists public.staff_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password text not null,
    full_name text not null,
    role text not null default 'staff',
    created_at timestamptz not null default now()
);

create index if not exists repair_tickets_room_idx on public.repair_tickets (room_number);
create index if not exists repair_tickets_status_idx on public.repair_tickets (status);
create index if not exists students_room_idx on public.students (room_number);

-- API ปัจจุบันทำงานผ่าน Netlify Function โดยใช้ Supabase key จาก environment
grant select, insert, update, delete on public.rooms to anon, authenticated;
grant select, insert, update, delete on public.students to anon, authenticated;
grant select, insert, update, delete on public.repair_tickets to anon, authenticated;
grant select, insert, update, delete on public.utility_rates to anon, authenticated;
grant select, insert, update, delete on public.staff_users to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

